/* eslint no-unused-vars: off */
/* eslint no-global-assign: off */
/* global systemDictionary */
/*
+===================== DO NOT MODIFY ======================+
| This file was generated by translate-adapter, please use |
| `translate-adapter adminLanguages2words` to update it.   |
+===================== DO NOT MODIFY ======================+
*/
"use strict";

systemDictionary = {
    "speedport adapter settings": {
        "en": "Adapter settings for speedport",
        "de": "Adaptereinstellungen für speedport",
        "ru": "Настройки адаптера для speedport",
        "pt": "Configurações do adaptador para speedport",
        "nl": "Adapterinstellingen voor speedport",
        "fr": "Paramètres d'adaptateur pour speedport",
        "it": "Impostazioni dell'adattatore per speedport",
        "es": "Ajustes del adaptador para speedport",
        "pl": "Ustawienia adaptera dla speedport",
        "uk": "Налаштування адаптера для speedport",
        "zh-cn": "speedport的适配器设置"
    },
    "option1": {
        "en": "option1",
        "de": "Option1",
        "ru": "вариант 1",
        "pt": "opção1",
        "nl": "optie1",
        "fr": "option1",
        "it": "opzione1",
        "es": "opción1",
        "pl": "opcja 1",
        "uk": "варіант1",
        "zh-cn": "选项1"
    },
    "option2": {
        "en": "option2",
        "de": "Option2",
        "ru": "вариант 2",
        "pt": "opção2",
        "nl": "optie2",
        "fr": "option2",
        "it": "opzione2",
        "es": "opción2",
        "pl": "opcja 2",
        "uk": "варіант2",
        "zh-cn": "选项2"
    }
};